export { default as homeIcon } from './homeIcon.vue'
export { default as exitIcon } from './exitIcon.vue'
export { default as triangleIcon } from './triangleIcon.vue'
export { default as starIcon } from './starIcon.vue'
export { default as forkIcon } from './forkIcon.vue'
