export * as trendings from './rest/trendings.js'
export * as readme from './rest/readme.js'
export * as starred from './rest/starred.js'
export * as user from './rest/user.js'
export * as auth from './rest/auth.js'
export * as issues from './rest/issues.js'
